# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMaxVisibleItems(20)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 90))
        self.label.setMaximumSize(QtCore.QSize(16777215, 90))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 90))
        self.label_2.setMaximumSize(QtCore.QSize(90, 90))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Carnival-AU"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Azamara"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Carnival-US"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Celebrity"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Costa"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Cunard"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Holland-America"))
        self.comboBox.setItemText(7, _translate("MainWindow", "NCL"))
        self.comboBox.setItemText(8, _translate("MainWindow", "OceaniaCruises"))
        self.comboBox.setItemText(9, _translate("MainWindow", "OceaniaCruisesCOP"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Orbitz"))
        self.comboBox.setItemText(11, _translate("MainWindow", "P-O-AU"))
        self.comboBox.setItemText(12, _translate("MainWindow", "P-O-UK"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Princess"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Royal-Caribbean"))
        self.comboBox.setItemText(15, _translate("MainWindow", "RSSC"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Seabourn"))
        self.pushButton.setText(_translate("MainWindow", "Download"))

