# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 295)
        MainWindow.setMinimumSize(QtCore.QSize(400, 250))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setMaximumSize(QtCore.QSize(70, 70))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Downloader"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Azamara"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Carnival Australia"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Carnival.com"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Celebrity"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Costa"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Cunard"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Disney"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Holland America"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Norwegian Cruise Lines"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Oceania Cruises Non Cruise only prices"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Oceania Cruises Cruise only prices"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Orbitz"))
        self.comboBox.setItemText(13, _translate("MainWindow", "P&O Australia"))
        self.comboBox.setItemText(14, _translate("MainWindow", "P&O UK"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Princess"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Royal Caribbean"))
        self.comboBox.setItemText(17, _translate("MainWindow", "RSSC"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Seabourn"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Silversea"))
        self.comboBox.setItemText(20, _translate("MainWindow", "All"))
        self.pushButton.setText(_translate("MainWindow", "Download Selected"))

